name: Сборка Net Proxy Manager

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Manager/**'
  pull_request:
    paths:
      - 'Manager/**'

jobs:
  build:
    name: Сборка APK
    runs-on: ubuntu-latest

    steps:
      - name: Получение кода
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Подготовка ключей подписи
        # Условие: если это не pull_request и ветка main, либо если это тег
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/main' ) || github.ref_type == 'tag' }}
        working-directory: Manager
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo storePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile=$PWD/'key.jks' >> keystore.properties
            echo '${{ secrets.KEY_STORE }}' | base64 --decode > key.jks
          fi

      - name: Настройка Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Настройка Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Сборка APK
        working-directory: Manager
        run: |
          ./gradlew assemble

      - name: Загрузка Release APK
        uses: actions/upload-artifact@v7
        with:
          name: "NetProxy-release"
          path: "Manager/app/build/outputs/apk/release/*.apk"
          compression-level: 9

      - name: Загрузка Release Mapping (карта соответствий)
        uses: actions/upload-artifact@v7
        with:
          name: "NetProxy-release-mappings"
          path: "Manager/app/build/outputs/mapping/release"
          compression-level: 9

      - name: Загрузка Debug APK
        uses: actions/upload-artifact@v7
        with:
          name: "NetProxy-debug"
          path: "Manager/app/build/outputs/apk/debug/*.apk"
          compression-level: 9
